apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: misterpvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
     requests:
       storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coordinator
  labels:
    app: coordinator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coordinator
  template:
    metadata:
      labels:
        app: coordinator
    spec:
      volumes:
      - name: files
        persistentVolumeClaim:
          claimName: misterpvc
      containers:
      - name: coordinator
        image: coordinator:1
        volumeMounts:
        - mountPath: /files
          name: files
        ports:
        - containerPort: 1234
      initContainers:
      - name: init-coordinator
        image: fetch:1
        volumeMounts:
        - mountPath: /files
          name: files
---
apiVersion: v1
kind: Service
metadata:
  name: coordinator
  labels:
    app: coordinator
spec:
  selector:
    app: coordinator
  ports:
  - port: 1234
    targetPort: 1234
    protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dashboard
  labels:
    app: dashboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dashboard
  template:
    metadata:
      labels:
        app: dashboard
    spec:
      volumes:
      - name: files
        persistentVolumeClaim:
          claimName: misterpvc
      containers:
      - name: dashboard
        image: dashboard:1
        volumeMounts:
        - mountPath: /files
          name: files
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: dashboard
  labels:
    app: dashboard
spec:
  type: NodePort
  selector:
    app: dashboard
  ports:
    - port: 80
      targetPort: 80
      nodePort: 32000
